import AppKit
import Foundation

struct PasteboardPayload {
    let imageItem: NSPasteboardItem
    let fileURL: URL

    var objects: [NSPasteboardWriting] {
        [imageItem, fileURL as NSURL]
    }

    init(pngData: Data, fileURL: URL) {
        self.fileURL = fileURL

        let item = NSPasteboardItem()
        item.setData(pngData, forType: .png)
        item.setData(Data("1".utf8), forType: .commandVGenerated)
        item.setData(Data("1".utf8), forType: .autoGenerated)

        if
            let image = NSImage(data: pngData),
            let tiffData = image.tiffRepresentation
        {
            item.setData(tiffData, forType: .tiff)
        }

        self.imageItem = item
    }
}

extension NSPasteboard.PasteboardType {
    static let commandVGenerated = NSPasteboard.PasteboardType("io.github.serkanemir.cmdv.generated")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}
